### ISSUE TITLE
Source image of cover is incorrect

### ISSUE THREAD

**Issue by rayriffy** [aomkirby123/opener-api#2]
https://opener.now.sh/api/data/252823

### Expected result

```
    "cover": {
      "t": "p",
      "w": 350,
      "h": 494,
      "src": "https://t.nhentai.net/galleries/1313829/cover.png"
    },
```

### Actual result

```
    "cover": {
      "t": "p",
      "w": 350,
      "h": 494,
      "src": "https://t.nhentai.net/galleries/1313829/cover.jpg"
    },
```

**Comment by SaltyAom** [comment]
Ok, I get it. Looks like NH does re-structure their own API, I guess? Otherwise something just went wrong and I don't know how to solve it (or I might be too lazy).
![Oh no](https://www.elsetge.cat/myimg/f/23-233767_related-wallpaper-anime-meme-megumin.jpg)
But don't worry, I'm gonna rewrite this API very imminent time since this codebase is very hard to read.

**Comment by SaltyAom** [comment]
## Thanks for your patient, New API is now up!
<img width="1552" alt="New nhOpener API" src="https://user-images.githubusercontent.com/35027979/70800594-3312bd00-1ddf-11ea-9029-e692e78f332c.png">

Sooo~ new API has just been implement! Surely it take me some time off designing new structure with  
**a lot cleaner** usage. You might want to see the API itself which moved to [here](https://api.nhopener.mystiar.com) `https://api.nhopener.mystiar.com`.
  
This new version of the API should resolve this problem (although I haven't tried it, but it should have). Otherwise the code is quite pretty clean as I said to myself. You might want to take a look at [the source code](https://github.com/SaltyAom/nhopener/tree/master/api) and believe me, you will surely want to look at it.
  
If you have any problem or any unclear instruction you can always re-open this issue~~

**Comment by SaltyAom** [comment]
Btw, the main one is now stuck on cache which took 6 hours to resolve. You might want to test the API with [https://nhopener-api.now.sh/252823](https://nhopener-api.now.sh/252823) instead.
<img width="1552" alt="Screen Shot 2562-12-13 at 19 51 56" src="https://user-images.githubusercontent.com/35027979/70801657-057b4300-1de2-11ea-8df0-54b4f8a0c28a.png">
<img width="1552" alt="Screen Shot 2562-12-13 at 19 52 03" src="https://user-images.githubusercontent.com/35027979/70801664-09a76080-1de2-11ea-9e35-2f6e6fe4e38b.png">
